name: CICD-pipeline

# manual click to start run workflow
on: 
 workflow_dispatch:
   inputs:
     environments: 
       description: This is the option for select environment values
       default: "dev"
       required: true
       type: choice
       options:
         - dev
         - stag
         - prod
         
 # every job needs a seperate runner that is called parallelism
jobs:
  code: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code Clone form github"
  build:
    if: inputs.environments == 'dev'
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build docker containers
        run: echo "build docker image"
  test: 
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the containers
        run: echo "check containers are running or not"
  deploy: 
    if: inputs.environments == 'dev'
    needs: [code,build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo "code deploy successfully"
